### ISSUE TITLE
HTTP Error 502.5 - Process Failure 

### ISSUE THREAD

**Issue by crAZiAc** [RemiBou/Toss.Blazor#1]
HTTP Error 502.5 - Process Failure  

After git clone, restore and run in VS2017

Excellent initiative BTW, I've been looking for sometime for this concept of implementing asp.net core auth in Blazor.

**Comment by RemiBou** [comment]
did you start cosmosdb local emulator ?

**Comment by RemiBou** [comment]
you need to run only the server part, does the test passes ?

**Comment by crAZiAc** [comment]
I will try that. Thanks! I'll get back to you.

Groeten,

Tom de Ridder
________________________________
Van: Rémi BOURGAREL <notifications@github.com>
verzonden: maandag 2 juli 2018 22:39
Aan: RemiBou/Toss.Blazor
Cc: Tom de Ridder; Author
Onderwerp: Re: [RemiBou/Toss.Blazor] HTTP Error 502.5 - Process Failure (#1)


did you start cosmosdb local emulator ?

**Comment by crAZiAc** [comment]
I installed CosmosDB emulator and updated to .net core 2.1.1 official. It now works. Great job!
