### ISSUE TITLE
Authentication Details

### ISSUE THREAD

**Issue by crAZiAc** [RemiBou/Toss.Blazor#2]
Hi, I am trying to use the authentication part of your project in my own project.

However, I am using ASP.NET tables on SQL to do the auth using Microsoft accounts. I have ported the auth code succesfully and I am able to log in. However: when doing calls on the AcccountController, the server does not know I have logged in. How is this handled in your project? Does the client get authed? And how does the client know this? Using cookies maybe?

Could you try and explain a little bit about the auth process in your project? It would be greatly appreciated.

**Comment by RemiBou** [comment]
did you check the MVC middleware is inserted after the authentication middleware on your Startup.cs ? (method Configure) I met this problem before, it's difficult to troubleshoot.
```

  app.UseAuthentication();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "/api/{controller}/{action}/{id?}");
            });
```

**Comment by RemiBou** [comment]
I close it. If you still have the error please send more details
